### ISSUE TITLE
Install Problems.

### ISSUE THREAD

**Issue by chanharryc** [horryruo/multi-bot#1]
Hi,

I got the return after start by entry python3 mybot.py

Traceback (most recent call last):
  File "mybot.py", line 8, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
  File "/home/chanharry/.local/lib/python3.8/site-packages/telegram/ext/__init__.py", line 25, in <module>
    from .callbackcontext import CallbackContext
  File "/home/chanharry/.local/lib/python3.8/site-packages/telegram/ext/callbackcontext.py", line 21, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/home/chanharry/.local/lib/python3.8/site-packages/telegram/__init__.py)

May I know what is the issue and how I can fix?

Beside in the config.ini do i need cloudflare account for global key?
If need what authority do I need to set in cloudflare.

Thank you So much!

{Harry

**Comment by horryruo** [comment]
This seems to be a problem with python-telegram-bot, you can rerun pip3 install -r requirements.txt, or reinstall python-telegram-bot separately and try again.
cloudflare Global API Key in account setting,and  cannot be used for freenom's free domain

**Comment by chanharryc** [comment]
> This seems to be a problem with python-telegram-bot, you can rerun pip3 install -r requirements.txt, or reinstall python-telegram-bot separately and try again.
> cloudflare Global API Key in account setting,and cannot be used for freenom's free domain

Thank you so much. I had fix the problem. And I could use the bot.

However, when I check with command /uid the return often come out: Message is too long.
How can I fix it? This is the main feature for me. Thanks again.

**Comment by horryruo** [comment]
> > This seems to be a problem with python-telegram-bot, you can rerun pip3 install -r requirements.txt, or reinstall python-telegram-bot separately and try again.
> > cloudflare Global API Key in account setting,and cannot be used for freenom's free domain
> 
> Thank you so much. I had fix the problem. And I could use the bot.
> 
> However, when I check with command /uid the return often come out: Message is too long.
> How can I fix it? This is the main feature for me. Thanks again.

This is the function to get all the id of the actress in dmm, first you need to get the id of the girlfriend. For example, you can use the /cid function to get the exact id of the actress under that number-->1048277  
![image](https://user-images.githubusercontent.com/33121172/97006402-66cb8100-1572-11eb-902a-4e4eb6009e3e.png)



 and then copy the id to /uid 1048277  

![image](https://user-images.githubusercontent.com/33121172/97006496-8cf12100-1572-11eb-8610-46620e940180.png)

**Comment by chanharryc** [comment]
Thank you for your prompt reply.

Here is my situation
![IMG_5272](https://user-images.githubusercontent.com/66456293/97016296-27eff800-157f-11eb-84f7-3c0a420beade.jpg)
.

**Comment by horryruo** [comment]
> Thank you for your prompt reply.
> 
> Here is my situation
> ![IMG_5272](https://user-images.githubusercontent.com/66456293/97016296-27eff800-157f-11eb-84f7-3c0a420beade.jpg)
> .

This should be because the actress has too many numbers, which exceeds the limit of the number of words in telegram messages. I will try to separate the long messages later.

**Comment by chanharryc** [comment]
Thank you so much for your assistant.

**Comment by horryruo** [comment]
The telegram limit is 4096 characters. I can only implement hard segmentation for the time being, and it may break in the middle of the serial number. Currently, long messages have been implemented.

**Comment by horryruo** [comment]
> Thank you so much for your assistant.

It can be used at present, but the experience is slightly poor

**Comment by chanharryc** [comment]
It work very well in version 1.3. Thank you so much.
