### ISSUE TITLE
利用/links 指令獲取UID 

### ISSUE THREAD

**Issue by chanharryc** [horryruo/multi-bot#10]
你好

請問利用/links 指令獲取UID 是否可行? 很好時篩選好之後只需要提取UID, 但現在/links 指令是例出內容。
請問有沒有方法只提取UID 使用? 謝謝!

**Comment by horryruo** [comment]
现在已经支持，在/uid指令输入list链接获取全部uid

**Comment by chanharryc** [comment]
Thank you 原來一直支持

**Comment by chanharryc** [comment]
Thank you 原來一直支持
