### ISSUE TITLE
有需要的功能请提isuue

### ISSUE THREAD

**Issue by horryruo** [horryruo/multi-bot#11]
会看实现难度逐步添加

**Comment by MatrixDynamics** [comment]
大佬，是否接定制，需要定制几个tg机器人的功能

**Comment by horryruo** [comment]
> 大佬，是否接定制，需要定制几个tg机器人的功能

我技术很一般，业余自己学着写的。你在乐佬discord群吗，你可以搜索multi，就知道我的id私聊我，我看看难不难

**Comment by horryruo** [comment]
> 大佬，是否接定制，需要定制几个tg机器人的功能

我技术很一般，业余自己学着写的。你发邮件私聊联系我看看难不难吧 [horryruo@gmail.com](mailto:horryruo@gmail.com)
