### ISSUE TITLE
local variable 'media_group' referenced before assignment

### ISSUE THREAD

**Issue by lazybagabc** [horryruo/multi-bot#2]
.

**Comment by andywu19** [comment]
在使用命令 /video h_113sy00033之后，出现：
1.原视频超出telegram大小限制，将发送低画质版本，可复制原画质链接到浏览器查看!---https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_113sy00033/h_113sy00033_dmb_w.mp4
2.Failed to get http url content

这里没有发送低画质版本。

**Comment by horryruo** [comment]
> 在使用 命令 /photo ssni-520 之后，出现：local variable 'media_group' referenced before assignment

在添加超过10张图片功能时少加了一行，已修复

**Comment by horryruo** [comment]
> 在使用命令 /video h_113sy00033之后，出现：
> 1.原视频超出telegram大小限制，将发送低画质版本，可复制原画质链接到浏览器查看!---https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_113sy00033/h_113sy00033_dmb_w.mp4
> 2.Failed to get http url content
> 
> 这里没有发送低画质版本。
![image](https://user-images.githubusercontent.com/33121172/99803696-dda96900-2b74-11eb-8a3e-2733e0384238.png)

经过测试并没有复现错误，请确保更新最新版本

**Comment by horryruo** [comment]
> 在使用命令 /video h_113sy00033之后，出现：
> 1.原视频超出telegram大小限制，将发送低画质版本，可复制原画质链接到浏览器查看!---https://cc3001.dmm.co.jp/litevideo/freepv/h/h_1/h_113sy00033/h_113sy00033_dmb_w.mp4
> 2.Failed to get http url content
> 
> 这里没有发送低画质版本。

同时，如果你没有安装chrome使用selenium引擎，程序可能无法获取正确的视频链接，会采取正则形式类比获取，所以年代久远或者不符合规律的作品可能获得的链接不符合现在的规律
