### ISSUE TITLE
Bot returns errors: Message is too long

### ISSUE THREAD

**Issue by waahaa** [horryruo/multi-bot#3]
如果返回的单条数据过长，bot会报错：Message is too long
相关网页 ：https://core.telegram.org/method/messages.sendMessage#return-errors
查询月额时的cid：ddob00070,td030dv01275,2wdi00077,h_1323nikm00041,td029dv01264,jul00165,td029dv01254,td028dv01244,jufe00146,rbd00957,td028dv01235,td027dv01217,rbd00941,td023dv01175,pppd00790,td024dv01186,td024dv01197,shkd00866,jfb00178,jufe00063,meyd00449,jufe00050,td020dv01208,meyd00435,meyd00426,jbd00238,atid00340,meyd00404,meyd00389,jufe00005,jufd00991,jufd00980,jufd00964,atid00314,jufd00910,jufd00892,juy00462,jufd00875,juy00397,juy00368,juy00337,juy00306,juy00276,jufd00795,jufd00780,jufd00765,jufd00750,td005dv1227,jufd00737,jufd00723,juy00113,rki00435,shkd00721,jufd00647,jusd00722,jufd00636,jufd00623,jufd00613,jufd00598,jux00858,jux00836,jux00812,jufd00560,jufd00550,jux00727,jux00703,ure00027,mdyd00991,adn00068,supd00096,shkd00622,shkd00575,rbd00700,rbd00546,rbd00506,rbd00479,rbd00464,rbd00456,rbd00447,rbd00423,rbd00410,migd00519,mide00084,midd00997,mdyd00959,jux00363,jux00338,jux00315,jux00293,jux00182,jux00162,jusd00602,jufd00456,iptd00934,hnd00150,bf00225,atkd00203,atid00245,adn00061,53dv01235,53dv01227,53dv01217,53dv01208,53dv01197,53dv01186,53dv01175,53dv01287,53dv01275,53dv01264,53dv01254,53dv01244

**Comment by horryruo** [comment]
因为月额会有长表格，所以月额没有弄长消息切割，会显得很奇怪。建议不要一次性查询太多哦。telegram官方限制bot单消息4000字符。

**Comment by waahaa** [comment]
> 因为月额会有长表格，所以月额没有弄长消息切割，会显得很奇怪。建议不要一次性查询太多哦。telegram官方限制bot单消息4000字符。

我并不需要长表格，如果我需要关闭发送长表格，请问需要修改哪些代码呢？

**Comment by horryruo** [comment]
mybot.py    164行到176行删掉所有的`update.message.reply_text(tb)`，但是返回月额与非月额列表过长依旧会被telegram限制

**Comment by horryruo** [comment]
已经加了配置可以选择是否要表格，以及月额长消息分割

**Comment by waahaa** [comment]
> 已经加了配置可以选择是否要表格，以及月额长消息分割

Owesome! 简直光速！感谢！

**Comment by waahaa** [comment]
更新之后，发现了一个新问题，查询的还是上面提到的cid，bot会报错：Can't parse entities: can't find end of the entity starting at byte offset 188

**Comment by horryruo** [comment]
已修复

**Comment by waahaa** [comment]
> 已修复

Bravo，新版运行良好！感谢！
