### ISSUE TITLE
Can't parse entities: can't find end of the entity starting at byte offset 292

### ISSUE THREAD

**Issue by chanharryc** [horryruo/multi-bot#4]
部份UID 會報錯但部份會正常
/uid 1005358

會報告
Can't parse entities: can't find end of the entity starting at byte offset 292

但之前26/10時安裝的版本可以正常顯示
相澤リナ(あいざわりな) - エロ動画・アダルトビデオ - FANZA動画
page(1)(21),cid list  =>
41hodv020651,mibd00608,midd00735,midd00749,41hodv020664,midd00725,41hodv020674,midd00761,41bndv00796,41hodv020669,mibd00592,h_346gshrb00777,mibd00646,41bndv00810,41hodv020657,1sdmt00284,mibd00675,1sdmt00393,1sddl00479,41bndv00833,41bndv00827

**Comment by horryruo** [comment]
已修复

**Comment by chanharryc** [comment]
Thank you so much!
