### ISSUE TITLE
dmm查询不到的num或者cid，希望也能返回列表

### ISSUE THREAD

**Issue by mengx8** [horryruo/multi-bot#5]
下面是一个查询的例子：

/m MXGS-845,SNIS-595,MXGS-837,SNIS-575,MXGS-829,SNIS-552,SNIS-530,MXGS-811,SNIS-507,MXGS-803,SNIS-483,SNIS-460,MXGS-783
正在查询13个...请稍候......
月额list (12) => MXGS-837,MXGS-845,SNIS-460,MXGS-829,SNIS-507,SNIS-575,MXGS-811,SNIS-552,SNIS-595,MXGS-803,SNIS-530,SNIS-483

如果查询不到的num或者cid，还要去比对，这就很麻烦了，希望能把查询失败的也能返回列表

**Comment by horryruo** [comment]
有空我加上去

**Comment by horryruo** [comment]
> 下面是一个查询的例子：
> 
> /m MXGS-845,SNIS-595,MXGS-837,SNIS-575,MXGS-829,SNIS-552,SNIS-530,MXGS-811,SNIS-507,MXGS-803,SNIS-483,SNIS-460,MXGS-783
> 正在查询13个...请稍候......
> 月额list (12) => MXGS-837,MXGS-845,SNIS-460,MXGS-829,SNIS-507,SNIS-575,MXGS-811,SNIS-552,SNIS-595,MXGS-803,SNIS-530,SNIS-483
> 
> 如果查询不到的num或者cid，还要去比对，这就很麻烦了，希望能把查询失败的也能返回列表

已经添加了无结果列表返回功能

**Comment by mengx8** [comment]
> > 下面是一个查询的例子：
> > /m MXGS-845,SNIS-595,MXGS-837,SNIS-575,MXGS-829,SNIS-552,SNIS-530,MXGS-811,SNIS-507,MXGS-803,SNIS-483,SNIS-460,MXGS-783
> > 正在查询13个...请稍候......
> > 月额list (12) => MXGS-837,MXGS-845,SNIS-460,MXGS-829,SNIS-507,SNIS-575,MXGS-811,SNIS-552,SNIS-595,MXGS-803,SNIS-530,SNIS-483
> > 如果查询不到的num或者cid，还要去比对，这就很麻烦了，希望能把查询失败的也能返回列表
> 
> 已经添加了无结果列表返回功能

更新了，尝试了一下新功能可以用，但是没有返回无结果的总条数，可以加上吗

月额list (24) => SNIS-575,MXGS-845,SNIS-595,SNIS-703,MXGS-803,SNIS-507,MXGS-829,MXSPS-443,MXGS-876,SNIS-633,MXGS-884,MXGS-891,SNIS-665,SNIS-483,SNIS-723,MXGS-837,SNIS-530,MXGS-811,SNIS-614,MXGS-868,SNIS-683,SNIS-552,MXGS-854,SNIS-650
无结果 => MXGS-820,MXGS-793

**Comment by horryruo** [comment]
> > > 下面是一个查询的例子：
> > > /m MXGS-845,SNIS-595,MXGS-837,SNIS-575,MXGS-829,SNIS-552,SNIS-530,MXGS-811,SNIS-507,MXGS-803,SNIS-483,SNIS-460,MXGS-783
> > > 正在查询13个...请稍候......
> > > 月额list (12) => MXGS-837,MXGS-845,SNIS-460,MXGS-829,SNIS-507,SNIS-575,MXGS-811,SNIS-552,SNIS-595,MXGS-803,SNIS-530,SNIS-483
> > > 如果查询不到的num或者cid，还要去比对，这就很麻烦了，希望能把查询失败的也能返回列表
> > 
> > 
> > 已经添加了无结果列表返回功能
> 
> 更新了，尝试了一下新功能可以用，但是没有返回无结果的总条数，可以加上吗
> 
> 月额list (24) => SNIS-575,MXGS-845,SNIS-595,SNIS-703,MXGS-803,SNIS-507,MXGS-829,MXSPS-443,MXGS-876,SNIS-633,MXGS-884,MXGS-891,SNIS-665,SNIS-483,SNIS-723,MXGS-837,SNIS-530,MXGS-811,SNIS-614,MXGS-868,SNIS-683,SNIS-552,MXGS-854,SNIS-650
> 无结果 => MXGS-820,MXGS-793

加上了
